import { defineConfig } from "oxfmt";

export default defineConfig({
	arrowParens: "avoid",
	semi: true,
	singleQuote: false,
	trailingComma: "all",
	printWidth: 120,
	useTabs: true,
	tabWidth: 2,
	endOfLine: "lf",
	sortPackageJson: {
		sortScripts: true,
	},
	sortImports: {
		newlinesBetween: false,
		groups: [
			["value-builtin", "value-external"],
			["value-internal", "value-parent", "value-sibling", "value-index"],
			"type-import",
			"unknown",
		],
	},
	// `docs/openapi.json` is generated by `export-openapi` and byte-compared in tests;
	// `docs/errors.md` is kept row-for-row in sync with `ErrorCode`. Neither is ours to reformat.
	ignorePatterns: ["packages/**", "**/node_modules/**", "pnpm-lock.yaml", "docs/**"],
	overrides: [
		{
			files: ["**/*.toml"],
			options: {
				useTabs: false,
			},
		},
	],
});
